version: '2'

services:
  app:
    image: lpa/php-nginx
    ports:
    - 8080:80
    volumes:
    - .:/var/www
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    - ./clevercloud:/etc/supervisor/conf.d:ro
